### ISSUE TITLE
floragunncom/sg-elasticsearch image contains demo certificates

### ISSUE THREAD

**Issue by ialidzhikov** [floragunncom/search-guard-helm#12]
##### Steps to reproduce

1. Run

```
$ docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" floragunncom/sg-elasticsearch:6.5.4-oss-24.2
```

2. Exec to the container and ensure that the demo certficates are installed.

```
$ docker exec -ti <container-id> sh
$ ls -la config/
total 48
drwxrwxr-x 1 elasticsearch root 4096 Mar 28 09:17 .
drwxrwxr-x 1 elasticsearch root 4096 Mar 20 00:35 ..
-rw-rw---- 1 elasticsearch root  207 Mar 28 09:17 elasticsearch.keystore
-rw-rw-r-- 1 elasticsearch root 1349 Mar 20 00:35 elasticsearch.yml
-rw-r--r-- 1 root          root 1704 Mar 20 00:35 esnode-key.pem
-rw-r--r-- 1 root          root 1720 Mar 20 00:35 esnode.pem
drwxrwx--- 2 elasticsearch root 4096 Dec 17 21:53 ingest-geoip
-rw-rw---- 1 elasticsearch root 3194 Dec 17 21:15 jvm.options
-rw-r--r-- 1 root          root 1704 Mar 20 00:35 kirk-key.pem
-rw-r--r-- 1 root          root 1610 Mar 20 00:35 kirk.pem
-rw-rw-r-- 1 elasticsearch root  285 Dec 17 21:52 log4j2.properties
-rw-r--r-- 1 root          root 1444 Mar 20 00:35 root-ca.pem
```

This prevents users to use `allow_unsafe_democertificates: false` because error occurs that demo certificates exist.
The workaround done in chart is:

```
lifecycle:
  postStart:
    exec:
      command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash +e
        shopt -s dotglob
        rm -f /usr/share/elasticsearch/config/*.pem
```

https://github.com/floragunncom/search-guard-helm/blob/master/sg-helm/templates/_helpers.tpl#L29

I would prefer the opposite - the image to do not contain demo certs and if you want to use them, you just install them with hook/init container. I think this should be approach. WDYT?
