### ISSUE TITLE
Ingress support  ?

### ISSUE THREAD

**Issue by sandeepbangera** [floragunncom/search-guard-helm#16]
Is there a plan to add ingress support to the helm chart. This will allow to expose the SG/ES/Kibana endpoints using proper DNS names and certs.  ES and Kibana standalone helm charts do come with this support e.g. https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml

**Comment by sandeepbangera** [comment]
In most production k8s envs we would have `svc`for endpoints  of type `ClusterIP` and  a ingress controller running and have ingress rules defined for all endpoints which need to be exposed to the outside world. Having ingress rules also helps automating creating certs and registering with DNS servers using `cert-manager` and `external-dns` k8s tools. I know the current  helm chart exposes `svc` of  type `LoadBalancer` but would be nice to have ingress support added.

I was able to get this working using the below `Ingress`. It would be nice if you could add this to your existing helm templates so it could be of use to other searchguard customers.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: searchguard
  labels:
    component: searchguard-sg-helm
    role: kibana
  annotations:
     kubernetes.io/ingress.class: nginx
 
spec:
  tls:
    - hosts:
      - my.searchguard.com
      secretName: kibana-tls

  rules:
    - host: my.searchguard.com
      http:
        paths:
          - path: /
            backend:
              serviceName: searchguard-sg-helm
              servicePort: 5601
```

Users could feed in the parameters from values.yaml 

```
  ingress:
    enabled: true

    annotations:
       kubernetes.io/ingress.class: nginx

    ## List of hosts for the ingress
    hosts:
      - my.searchguard.com

    tls:
      - hosts:
          - my.searchguard.com
        secretName: searchguard-tls
```
