### ISSUE TITLE
Support to update sg-config.yml

### ISSUE THREAD

**Issue by sandeepbangera** [floragunncom/search-guard-helm#20]
Would be nice to have support to add custom configuration to  sg-config.yml. Currently there is support to configure only for sg_internal_users.yml, sg_roles_mapping.yml, sg_roles.yml.

For e.g. customers may want to add additional authc:<>_auth_domain in sg-config.yml

**Comment by sandeepbangera** [comment]
In my particular use case I wanted to update `sg-config.xml` to add proxy authentication.

I ended up directly updating the template file.
`search-guard-helm/sg-helm/templates/searchguard-configmap_ES7.yaml`

```
  sg_config.yml: |-
    _sg_meta:
      type: "config"
      config_version: 2
    sg_config:
      dynamic:
        do_not_fail_on_forbidden: {{ .Values.common.do_not_fail_on_forbidden }}
        http:
          anonymous_auth_enabled: false
          xff:
            enabled: true
            internalProxies: '.*'
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            transport_enabled: false
            order: 1
            http_authenticator:
              type: basic
              challenge: false
            authentication_backend:
              type: intern
          proxy_auth_domain:
            description: "Authenticate via proxy"
            http_enabled: true
            transport_enabled: false
            order: 0
            http_authenticator:
              type: proxy
              challenge: false
              config:
                user_header: "x-auth-username"
                roles_header: "x-auth-roles"
            authentication_backend:
              type: noop

``` 

It would have been nice if I could specify this in my `values.yaml` so I did not need to update the template file directly. I am sure other customers would also need to update `sg-config.yml` for other customizations.

In the documentation you suggest using `sgadmin.sh`, But would be safer and more user friendly to do this at deployment time.
